package br.org.gdt.enums;

public enum FpEnumEventos {

    Salario,
    HorasExtras50,
    HorasExtras100,
    HorasNoturnas,
    HorasFaltas,
    INSS,
    FGTS,
    IRRF,
    PensaoJudicialFixo,
    PensaoJudicialMinimo,
    PensaoJudicialPorcentagem,
    SalarioFamilia,
    SalarioMaternidade,
    Insalubridade10,
    Insalubridade20,
    Insalubridade40,
    Periculosidade,
    Transporte,
    Alimentacao,
    Refeicao,
    PlanoSaude,
    ContribuicaoSindical,
    GratificacoesDiversas,
    AuxilioDoenca,
    DSR,
}
